"""initial

Revision ID: ffffe4416ce5
Revises: 
Create Date: 2024-09-26 02:53:59.842171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffffe4416ce5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['categories.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('problem_tags')
    op.drop_table('problem')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_problem', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('index', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('contestid', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('solvedcount', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('problem_tags',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_problem', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.drop_table('movies')
    op.drop_table('categories')
    # ### end Alembic commands ###
